# Generated by Django 4.2.3 on 2023-08-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0003_sprofile_tprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SProfile',
        ),
    ]
