# Generated by Django 4.2.3 on 2023-08-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0005_sprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfimage',
            field=models.ImageField(default='demoprofile.png', upload_to='Profiles/'),
        ),
    ]
