# Generated by Django 4.2.3 on 2023-08-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0006_user_pfimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pfimage',
            new_name='pfimg',
        ),
    ]
