# Generated by Django 4.2.3 on 2023-08-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0008_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='usr_id',
            new_name='usr',
        ),
    ]
